name: flame_oxygen
description: Integrate the Oxygen ECS with the Flame Engine.
version: 0.1.2
homepage: https://github.com/flame-engine/flame/tree/main/packages/flame_oxygen

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.1.1
  oxygen:
    git:
      url: https://github.com/natebot13/oxygen.git
      ref: hasnot-fix

dev_dependencies:
  dartdoc: ^4.1.0
  flame_lint: ^0.0.1
